export enum Path {
  ADMIN = '/admin',
  CALLBACK_GITHUB = '/api/auth/callback/github',
  CALLBACK_GOOGLE = '/api/auth/callback/google',
  ERROR_404 = '*',
  FORGOT_PASSWORD = '/auth/recovery',
  LOGIN = '/auth/login',
  NEW_PASSWORD = '/auth/new_password',
  NEW_PASSWORD_ERROR = '/auth/new_password/verificationError',
  PROFILE = '/profile',
  PROFILE_SETTINGS = '/profile/settings',
  REGISTRATION = '/auth/registration',
  REGISTRATION_ERROR = '/auth/registration/verificationError',
  REGISTRATION_SUCCESS = '/auth/registration/success',
  SIGNIN = '/auth/signinOAuth',
}
